# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build JsonEncryptor

on:
  workflow_dispatch:      # manual trigger

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./JsonEncryptor.csproj
    - name: Publish
      run: dotnet publish ./JsonEncryptor.csproj  --configuration release -r win-x64 -o published
    - name: Upload published app
      uses: actions/upload-artifact@v4
      with:
        name: JsonEncryptor
        path: published/**
        
